# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
#  vmImage: ubuntu-latest
   name: default

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'teams_sonarqube'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=teams-java-pipeline_teams-java-pipeline
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    sonarQubeRunAnalysis: true 
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: false
    findBugsRunAnalysis: true
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'